version: "3.9"
   
services:
  proxy:
    build: .
    image: aws_console_scanner
    ports:
      - "8080:8080"
    volumes:
      - ~/.mitmproxy:/root/.mitmproxy
    environment:
      - CERT_PASSWORD
